language: node_js
node_js:
  - '6'
  - '4'
before_script:
  - chmod +x fixtures/optipng-linux
  - chmod 755 fixtures/optipng-linux
  - chmod +x fixtures/optipng-osx
  - chmod 755 fixtures/optipng-osx
